# Generated by Django 3.2 on 2023-02-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
