# Generated by Django 3.2 on 2023-02-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_alter_enquiry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Enquiries'},
        ),
    ]
